apiVersion: v1
kind: Service
metadata:
  name: local-machine-port
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 31515
  selector:
    component: web3cacheipfs
