
apiVersion: v1
kind: Service
metadata:
  namespace: web3cache
  name: web3cacheread-service
  labels:
    component: web3cacheread
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /web3cache/read/healthcheck
spec:
  type: NodePort
  selector:
    component: web3cacheread
  ports:
    - port: 443
      targetPort: 3000
      nodePort: 30007