apiVersion: v1
kind: Service
metadata:
  namespace: web3cache
  name: web3cache-controller-service
  labels:
    component: web3cache-controller
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /web3cache/controller/healthcheck
spec:
  type: NodePort
  selector:
    component: web3cache-controller
  ports:
    - port: 5100
      targetPort: 5100
      nodePort: 30009
      name: https