apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web3cache
  name: web3cache-dispatcher
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web3cache-dispatcher
  template:
    metadata:
      labels:
        component: web3cache-dispatcher
    spec:
      containers:
        - name: web3cache-dispatcher-client
          image: ghcr.io/orangecomet/web3cache-dispatcher:stage
          imagePullPolicy: Always
          env:
            - name: CONSUMER_PORT
              value: "3003"
            - name: READ_URL
              value: "http://web3cacheread-service:443/web3cache/read"
            - name: REALTIME_URL
              value: "http://web3cache-realtime-service:4100/web3cache/realtime"
            - name: RUST_LOG
              value: "info"
            - name: MONGOURI
              valueFrom:
                secretKeyRef:
                  name: dispatcher-secrets
                  key: MONGOURI
          ports:
            - containerPort: 3003
              name: receiver
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "web3cache-dispatcher"
      imagePullSecrets:
        - name: dockerconfigjson-github-com
