name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["**"]
    tags:
      - "env/*"

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: ghcr.io/orangecomet/${{ github.event.repository.name }}:test
  DEV_TAG: ghcr.io/orangecomet/${{ github.event.repository.name }}:dev

jobs:
  pre_process:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.stripValue.outputs.cleanedRef }}
    steps:
      - name: Strip 'env/' from ref_name
        id: stripValue
        run: |
          REF_NAME=${GITHUB_REF#refs/tags/env/}
          echo "cleanedRef=${REF_NAME}" >> $GITHUB_OUTPUT
  # check-dependencies:
  #   name: cargo-hakari
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install cargo-hakari
  #       uses: taiki-e/install-action@v2
  #       with:
  #         tool: cargo-hakari
  #     - name: Manage Dependencies
  #       run: |
  #         cargo hakari generate --diff
  #         cargo hakari manage-deps --dry-run
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - name: Build | Lint
        run: cargo clippy
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo check
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions/checkout@v3
        with:
          rust-version: stable
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Run Rustfmt
        run: cargo fmt --all -- --check

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build dev image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "VERSION=${{ github.sha }}"
          tags: "dev:${{ github.sha }}"
          target: dev
          load: true
          cache-from: type=local,src=/tmp/buildx-cache
          cache-to: type=local,dest=/tmp/buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/buildx-cache \
          && mv /tmp/buildx-cache-new /tmp/buildx-cache

      - name: Run tests in dev container
        run: |
          docker run -e MONGOURI_TEST=${{ secrets.MONGO_TEST_URI }} dev:${{ github.sha }} cargo test --release

      - name: Build app
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            "VERSION=${{ github.sha }}"
          tags: "${{ github.sha }}"
          target: app
          load: true
          cache-from: type=local,src=/tmp/buildx-cache
          cache-to: type=local,dest=/tmp/buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/buildx-cache \
          && mv /tmp/buildx-cache-new /tmp/buildx-cache

  deploy-n-build:
    if: startsWith(github.ref, 'refs/tags/env/') && needs.build_and_test.result == 'success'
    runs-on: ubuntu-latest
    needs:
      - pre_process
      - Rustfmt
      - lint
      - build_and_test
      - compile
    environment:
      name: ${{ needs.pre_process.outputs.env_name }}
    steps:
      - name: Determine environment
        id: determine-env
        run: echo "ENV_NAME=${{ needs.pre_process.outputs.env_name }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker deployment metadata
        id: metadeployment
        uses: docker/metadata-action@v4
        with:
          tags: |
            deployment-${{ env.ENV_NAME }}
            deployment-${{ github.sha }}
            type=sha
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            ${{ env.ENV_NAME }}
            ${{ github.sha }}
            type=sha
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker deployment
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            ENV_NAME=${{ env.ENV_NAME }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadeployment.outputs.tags }}
          labels: ${{ steps.metadeployment.outputs.labels }}
          target: deployment

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            ENV_NAME=${{ env.ENV_NAME }}
            VERSION=${{ github.sha }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: app
          cache-from: type=local,src=/tmp/buildx-cache

      - name: Logging Kubernetes info
        run: |
          lowercase_image_name=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          echo "ENVNAME $ENV_NAME == ${GITHUB_REF#refs/heads/env/}"
          echo "IMAGE_NAME_LOWER=$lowercase_image_name" >> $GITHUB_ENV
          echo "Image Name (Lowercase): $lowercase_image_name"
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Docker Metadata Digest: ${{ github.sha }}"
          echo "Constructed Image with Digest: ${{ env.REGISTRY }}/$lowercase_image_name:${{ github.sha }}"

      - name: Deploy to k8s
        run: |
          curl -X POST \
          -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
          -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
          -H "Content-Type: application/json" \
          -d '{
                "container_spec": "${{ vars.CONTAINER_SPEC }}",
                "image": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}",
                "tag": "${{ github.sha }}",
                "namespace": "${{ vars.NAMESPACE }}",
                "deployment_name": "${{ vars.DEPLOYMENT_NAME }}",
                "dry_run": false
            }' \
          ${{ secrets.DEPLOYER_URL }}/deploy
