apiVersion: v1
kind: Service
metadata:
  namespace: web3cache
  name: web3cache-dispatcher-service
  labels:
    component: web3cache-dispatcher
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /web3cache/events/healthcheck
spec:
  type: NodePort
  selector:
    component: web3cache-dispatcher
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30002
      name: receiver
