apiVersion: v1
kind: Service
metadata:
  namespace: web3cache
  name: web3cache-subscriptions-service
  labels:
    component: web3cache-subscriptions
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /web3cache/events/healthcheck
spec:
  type: NodePort
  selector:
    component: web3cache-subscriptions
  ports:
    - port: 443
      targetPort: 3000
      nodePort: 30001
      name: https